# Generated by Django 4.0.6 on 2022-08-08 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_level', models.IntegerField()),
                ('description_level', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='home/static/placeholder.png', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usercategory'),
        ),
    ]
