# Generated by Django 4.0.6 on 2022-08-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_level_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(default='User', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.usercategory'),
        ),
    ]
